REPORT ZOOPS_D6_P3.

********** DAY 6 PROGRAM 3 ****************

"""" TOPICS - 1) STATIC CONSTRUCTORS, 2) INSTANCE CONSTUCTORS.

"""" SUMMARY - STATIC CONSTUCTORS WILL BE EXECUTED ONLY ONCE IN THE LIFETIME OF ENTIRE CLASS.
""""           WHEREAS INSTANCE CONSTRUCTOR GETS EXECUTED ON BEHALF OF EACH OBJECT.



"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

CLASS LCL_ABC DEFINITION.
  PUBLIC SECTION.
    METHODS CONSTRUCTOR.                                """" INSTANCE CONSTRUCTOR CAN CONTAIN IMPORTING PARAMETER AND EXCEPTION.
    CLASS-METHODS CLASS_CONSTRUCTOR.                    """" STATIC CONSTRUCTOR.CLASS-METHODS CLASS_CONSTRUCTOR IMPORTING X TYPE I.  ERROR - CAN'T CONTAIN ANY PARAMTER OR EXCEPTION.






ENDCLASS.


CLASS LCL_ABC IMPLEMENTATION.
  METHOD CONSTRUCTOR.
    WRITE :/ 'INSIDE INSTANCE CONSTRUCTOR'.
  ENDMETHOD.

  METHOD CLASS_CONSTRUCTOR.
    WRITE :/ 'INSIDE STATIC CONSTRUCTOR'.
  ENDMETHOD.



ENDCLASS.


START-OF-SELECTION.

FORMAT COLOR 1.
WRITE :/ 'FIRST OBJECT OB1 CREATED AND CHECKING IN WHAT SEQUENCE IT WOULD BE EXECUTED.'.


DATA OB1 TYPE REF TO LCL_ABC.
CREATE OBJECT OB1.


"""" NOTE - SO STATIC CONSTRUCTOR WILL BE EXECUTED BEFORE INSTANCE CONSTRUCTOR.
WRITE :/ 'STATIC INSTANCE EXECUTED BEFORE INSTANCE CONSTRUCTOR'.
FORMAT COLOR OFF.

ULINE.

FORMAT COLOR 2.
WRITE :/ 'SECONF OBJECT OB1 CREATED AND IT SHOWS ONLY INSTANCE CONSTRUCTOR WILL BE EXECUTED AGAIN.'.


DATA OB2 TYPE REF TO LCL_ABC.
CREATE OBJECT OB2.


"""" NOTE - SO STATIC CONSTRUCTOR WILL BE EXECUTED ONCE AND INSTANCE CONSTRUCTOR CAN BE EXECUTED ANY NUMBER OF TIMES.

WRITE :/ 'STATIC INSTANCE EXECUTED ONE TIME WHILE INSTANCE CONSTRUCTOR  CAN BE EXECUTED ANY NUMBER OF TIME AFTER CREATING THE OBJECT'.
FORMAT COLOR OFF.

ULINE.


FORMAT COLOR 3.
WRITE :/ 'SECOND OBJECT OB1 CREATED AND IT SHOWS ONLY INSTANCE CONSTRUCTOR WILL BE EXECUTED AGAIN.'.


DATA OB3 TYPE REF TO LCL_ABC.
CREATE OBJECT OB3.


"""" NOTE - .

WRITE :/ 'STATIC INSTANCE EXECUTED ONE TIME WHILE INSTANCE CONSTRUCTOR  CAN BE EXECUTED ANY NUMBER OF TIME AFTER CREATING THE OBJECT'.
FORMAT COLOR OFF.

ULINE.



























"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
