REPORT ZOOPS_D9_P1.

******************* DAY 9 PROGRAM 1 ****************************

"""" TOPICS - 1) ABSTRACT CLASS, 2) NARROW CASTING, 3) DYNAMIC CALLING.




""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"""" THEORY

"""" EARLIER      CLASS -> DEFINITION -> DECLARING METHODS (5 METHODS).
"""" ABSTRACT CLASS -> CLASS WHICH CONTAINS ATLEAST  ONE ABSTRACT METHOD(A METHOD WHICH IS JUST DECLARED AND NOT IMPLEMENTED.)
"""" NARROW CASTING - ASSINGING SUBCLASS OBJECT TO SUPER CLASS REFERENCE. THIS IS CALLED AS NARROW CASTING.
"""" DYNAMIC CALLING - IN THE COMPILATION TIME IT WILL NOT CHECK TO WHICH CLASS THIS METHOD BELONGS IN THE RUNTIME IT WILL CHECK IN WHICH CLASS THIS METHOD IS AVAILABLE.

"""" NOTE - IF THE CLASS CONTAINS ATLEAST ONE ABSTRACT METHOD THEN THE CLASS SHOULD ALSO BE DECLARED AS ABSTACT CLASS. WE WILL NEVER CREATE OUR OWN ABSTRACT CLASSES.
""""        WE SHOULD KNOW HOW TO WORK WITH ABSTRACT CLASSES WE WILL NEVER BE CREATING ABSTRACT CLASS.
""""        IF THE CLASS IS ABSTRACT THAT CLASS CANNOT BE INSTANTIATED MEANS WE CAN'T CREATE THE OBJECT FOR ABSTRACT CLASS.
""""        WE CAN CREATE THE OBJECT ONLY IF ALL THE METHODS ARE IMPLEMENTED.


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"""" Q - WHY A METHOD IS DECLARED AS ABSTRACT METHOD
"""" A - THE SAME METHOD HAS TO BE USED IN OTHER CLASSES BUT THE IMPLEMENTATION IS SPECIFIC TO THAT PARTICULAR CLASSES, IN THAT CASES WE DECLARE A METHOD AS ABSTRACT.

"""" Q - BY USING SUPER CLASS OBJECT CAN WE CALL SUBCLASS METHOD?
"""" A- YES WITH THE HELP OF NARROW CASTING AND DYNAMIC CALLING.

"""" Q - CAN WE CREATE THE OBJECTS FOR ABSTRACT CLASSES?
"""" A - WE CAN'T DIRECTLY INSTANTIATE ABSTRACT CLASSES BUT ONCE THE ABSTRACT CLASS , ABSTRACT METHODS ARE IMPLEMENTED IN THE SUBCLASS WE CAN ASSIGN SUBCLASS OBJECT TO THE ABSTRACT CLASS REFERENCE SO THAT THAT REFERNCE BECOMES OBJECT.
""""     AND USING THAT OBJECT WE CAN CALL ABSTRACT CLASS METHODS AS WELL AS SUBCLASS METHODS.
""""     AND WE CALL THE SUBCLASS METHODS THROUGH DYNAMIC CALLING.
""""     DYNAMIC CALLING MEANS IN THE RUNTIME IT WILL DECIDE WHERE THE IMPLEMENTATION IS AVAILABLE.

"""" Q - CAN A SUPER CLASS OBJECT ACCESS SUB CLASS METHOD?
"""" A - DIRECTLY BY USING THE SUPER CLASS OBJECT WE CAN'T ACCESS THE SUB CLASS METHO, BUT ONCE WE DO THE NARROW CASTING(ASSING SUBCLASS OBJECT TO SUPERCLASS REFERENCE)
""""     SO THAT THE REFERENCE BECOMES OBJECT.  


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

"""" REQ - TO CREATE ABSTRACT CLASS(RESTAURENT) AND CHEQUE INHERITING FROM RESTAURENT
"""" NOTE - PAYMENT METHOD IS ABSTRCT SINCE A CUSTOMER CAN MAKE PAYMENT BY USING CHEQUE, CREDIT CARD OR DEBIT CARD, SO WE DON'T KNOW THE IMPLEMENTATION.
""""        THE METHOD IS SAME BUT THE IMPLEMENTATION IS SPECIFIC TO RESPECTIVE CLASS.
""""        THE CLASS WHICHEVER IS INHERITING SUBCLASS MUST IMPLEMENT ABSTRACT METHOD, OTHERWISE THAT  SUBCLASS SHOULD ALSO BE DECLARED AS ABSTRACT.
 """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

 CLASS LCL_RESTAURENT DEFINITION ABSTRACT.                                         """" NOTE - IF A CLASS CONTAINS EVEN ONE ABSTRACT METHOD THEM THE CLASS SHOULD ALSO BE DECLARED AS ABSTRACT CLASS.
   PUBLIC SECTION.
      METHODS : STORE,                                                    """" INSTANCE METHODS
                DISPLAY,                                                           """" THE METHODS WHICH WE IMPLEMENT S CALLED AS NON-ABSTRACT METHOD / CONCRETE METHOD.
                PAYMENT ABSTRACT.                                                  """" ABSTRACT KEYWORD USED FOR ABSTRACT METHOD SINCE WE DON'T WANT TO ADD IMPLEMENTATION.
                                                                                   """" ABSTRACT METHOD ALSO CALLED AS NON CONCRETE METHOD.

*      CLASS-METHODS M1 ABSTRACT.                                                   """" ERROR - CAN'T REDEFINE STATIC METHODS AND THUS SHOULDN'T BE DECLARED AS ABSTRACT.
*       METHODS M1 ABSTRACT FINAL.                                                  """" SYNTAX ERROR.



   PROTECTED SECTION.
      DATA : TABLENO TYPE I,                                              """" INSTANCE ATTRIBUTES.
             STEWARD TYPE STRING.

*      METHODS M3 ABSTRACT.                                               """" VALID.


*   PRIVATE SECTION.
*      METHODS M3 ABSTRACT.                                               """" PRIVATE METHODS CAN'T BE REDEFINED AND THEREFORE MAYNOT BE DECLARED.

"""" NOTE - ABSTRACT METHODS ARE ALWAYS EITHER PUBLIC OR PROTECTED

ENDCLASS.


CLASS LCL_RESTAURENT IMPLEMENTATION.                                      """" SO OUT OF 3 METHODS WE DECLARED WE ARE IMPLEMENTING ONLY 2 METHODS.

  METHOD STORE.
    TABLENO = 4.
    STEWARD = 'RAJ'.

  ENDMETHOD.

  METHOD DISPLAY.
    WRITE :/ TABLENO, STEWARD.

  ENDMETHOD.


ENDCLASS.


"""" NOW CREATING A SUBCLASS WHICH HAS TO INHERIT SUPER CLASS LCL_RESTAURENT.

CLASS LCL_CHEQUE DEFINITION INHERITING FROM LCL_RESTAURENT.
  """" NOTE - IF A SUBCLASS INHERITS ANY ABSTRACT CLASS THAT SUBCLASS MUST COMPLUSORY REDEFINE THE ABSTRACT METHODS OF THE ABSTRACT CLASS(SUPERCLASS).

  PUBLIC SECTION.                                    """" TRYING TO CHANGE THE VISIBILITY, ERROR - YOU CAN'T CHANGE THE VISIBILITY WHEN REDEFING THE METHODS.
   METHODS PAYMENT REDEFINITION.
   METHODS DISPLAY REDEFINITION.
   METHODS SAYHELLO.

  PROTECTED SECTION.
    DATA : CHEQUENO TYPE I,
           CHEQUEDATE TYPE D,
           BANKNAME TYPE STRING,
           AMT TYPE I.



ENDCLASS.

CLASS LCL_CHEQUE IMPLEMENTATION.

  METHOD PAYMENT.
    CHEQUENO = 444.
    CHEQUEDATE = SY-DATUM.
    BANKNAME = 'ICICI BANK'.
    AMT = 453000.
  ENDMETHOD.

"""" NOTE - NOW CAN CREATE THE OBJECT FOR ABSTRACT METHODS SINCE ITS IMPLEMENTING THE ABSTRACT METHOD.

  METHOD DISPLAY.
    """" NOW SINCE THE WRITE METHOD IN THIS CLASS WILL ONLY DISPLAY THE RESULTS IN THE CHEQUE BUT WE NEED IT TO DISPLAY THE TABLENO ETC VALUE FROM SUPER CLASS.
    """" HENCE USING THE SUPER KEYWORD.

    CALL METHOD SUPER->DISPLAY.

    WRITE :/ CHEQUENO,CHEQUEDATE,BANKNAME,AMT.
  ENDMETHOD.

  METHOD SAYHELLO.
    WRITE :/ 'INSIDE DIRECT METHOD SAYHELLO OF CHEQUE CLASS'.
  ENDMETHOD.



ENDCLASS.





START-OF-SELECTION.

 DATA R TYPE REF TO LCL_RESTAURENT.
* CREATE OBJECT R.                        """" ERROR - YOU CANNOT GENERATE INSTANCES OF ABSTRACT CLASS.

 """" NOTE - NOW SINCE WE NEED TO ACCESS INSTANCE METHOD WE NEED TO CREATE REFERENCE.


 FORMAT COLOR 1.

 WRITE :/ 'CHEQUE CLASS OBJECT CQ...'.

 DATA CQ TYPE REF TO LCL_CHEQUE.
 CREATE OBJECT CQ.

 CALL METHOD : CQ->STORE,
               CQ->PAYMENT,
               CQ->DISPLAY,
               CQ->SAYHELLO.



 FORMAT COLOR OFF.


 FORMAT COLOR 2.

 WRITE :/ 'CHEQUE CLASS OBJECT CQ ASSIGNED TO ABSTRACT CLASS R'.

 R = CQ.                                   """" ASSINGING SUBCLASS OBJECT TO SUPER CLASS REFERENCE. THIS IS CALLED AS NARROW CASTING.
 CALL METHOD : R->STORE,
               R->PAYMENT,
               R->DISPLAY,
*               R->SAYHELLO.               """" NOTE - THIS IS CHECKED AT COMPILATION TIME """" ERROR - METHOD SAYHELLO IS UNKOWN... NOW THIS METHOD IS DECLARED ONLY INSIDE SUBCLASS.
               R->('SAYHELLO').              """" DYNAMIC CALLING.

 """" NOTE - WHENEVER WE ARE DOING NARROW CASTING BY USING THAT SUPER CLASS OBJECT WE CAN'T DIRECTLY ACCESS SUBCLASS METHOD.
 """" NOTE - BY USING THE THE SUPER CLASS OBJECT ALSO WE CAN ACCESS SUBCLASS METHOD USING DYNAMIC CALLING.

 FORMAT COLOR OFF.
 
 
