REPORT ZOOPS_D5_P2.

*********** DAY 5 PROGRAM 2 ***********


"""" TOPICS - USING GLOBAL CLASS FOR THE SAME PURPOSE.


"""" CREATED 2 CLASSES(1- ZCL_ABC2 & 2- ZCL_PQR2 ) WITH 3 METHODS IN CLASS ZCL_ABC2 AND 1 METHOD IN ZCL_PQR2.


DATA OB1 TYPE REF TO ZCL_PQR2.
CREATE OBJECT OB1.

CALL METHOD OB1->M4.

"""" NOW AFTER THE ABOVE INSIDE M4 IN GLOBAL CLASS ZCL_PQR2 CREATING ANOTHER OBJECT FOR THE OTHER CLASS.

"""" ADDED THE BELOW CODE IN M4 METHOD OF ZCL_PQR.

*DATA K TYPE REF TO LCL_ABC.              """" THIS SHOWS WE CAN CREATE OBJECTS INSIDE OTHER CLASS METHODS ALSO.
*     CREATE OBJECT K.

*CALL METHOD K->M1.



"""" NOW IN THE O/P WE ARE ABLE TO SEE BOTH WRITE STATEMENT OF M4 AND M1 WHICH WAS CALLED.



"""" NOW USING THE ABOVE OBJECT K WE WILL TRY TO CALL PROTECTED AND PRIVATE OBJECT AFTER ADDING THE ZCL_PQR2 AS FRIEND IN THE ZCL_ABC2.
"""" NOW IN THE OUTPUT ALL 4 METHODS IS VISIBLE.
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"""" ALL THE BELOW CODES THAT WERE ADDED TO ZCL_ABC2 CLASS.

*  method M1.
*    WRITE :/ 'INSIDE INSTANCE PUBLIC METHOD M1 OF LCL_ABC'.
*  endmethod.
*
*
*    method M2.
*    WRITE :/ 'INSIDE INSTANCE PUBLIC METHOD M2 OF LCL_ABC'.
*  endmethod.
*
*    method M3.
*    WRITE :/ 'INSIDE INSTANCE PUBLIC METHOD M3 OF LCL_ABC'.
*  endmethod.

"""" ALL THE BELOW CODES WERE ADDED TO ZCL_PQR2 CLASS.

*  method M4.
*
*
*    WRITE :/ 'INSIDE INSTANCE PUBLIC METHOD M4 OF LCL_PQR1'.
*
*
*""""  NOW CALLING THE OTHER GLOBAL CLASS LCL_ABC.
*    DATA K TYPE REF TO ZCL_ABC2.              """" THIS SHOWS WE CAN CREATE OBJECTS INSIDE OTHER CLASS METHODS ALSO.
*     CREATE OBJECT K.
*     CALL METHOD K->M1.
*
**     CALL METHOD K->M2. ERROR - SINCE ITS NOT YET FRIEND WITH ZCL_ABC2.
**     CALL METHOD K->M3.
*
*
*"""" NOTE - NOW WE ADDED METHOD ZCL_PQR AS FRIEND OF ZCL_ABC. IN THE FRIENDS TAB OF ZCL_ABC2 TYPE ZCL_PQR2.
*"""" NOW CALLING THE ABOVE PROTECTED AND PRIVATE METHOD.
*
*CALL METHOD K->M2.
*CALL METHOD K->M3.
*
*"""" THUS NOW THE ABOVE CODE WORKS AND WE DON'T HAVE THE CONCEPT OF DEFFERED AND GLOBAL CLASS IS SUFFICIENT.
*
*
*
*  endmethod.


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""\
