REPORT ZOOPS_D7_P2.

*********** DAY 7 PROGRAM 2 **************

"""" TOPICS - 1) USING GLOBAL CLASS WHICH IS MADE WITH USING CONCEPT OF INHERITANCE.

"""" NOTE - CAN USE FINAL KEYWORD TO MAKE THE CLASS AS FINAL AND WHICH CAN'T BE INHERITED,
"""" NOTE - FINAL CAN BE AT CLASS LEVEL AS WELL AS METHOD LEVEL.





""""""" CALLING THE PROGRAMS FROM CREATED CLASSES.

************************************************************************************

START-OF-SELECTION.

WRITE :/ 'OBJECT OB1 OF SUBCLASS LCL_CYCLE...'.

DATA OB1 TYPE REF TO ZCL_CYCLE.
CREATE OBJECT OB1.

CALL METHOD : OB1->SETCYCLE,
              OB1->DISPLAY.

ULINE.

WRITE :/ 'OBJECT OB2 OF SUBCLASS LCL_BIKE...'.

DATA OB2 TYPE REF TO ZCL_BIKE.
CREATE OBJECT OB2.

CALL METHOD : OB2->SETBIKE,
              OB2->DISPLAY.

ULINE.
