REPORT ZOOPS_D3_P1.


**************** OOPS DAY 3 PROGRAM 1 *****************


"""" TOPICS - 1)PASSING PARAMETERS TO METHODS. 2) IMPORTING AND EXPORTING PARAMETERS IN CALL METHOD.


"""" PARAMETERS TO METHODS - IMPORT , EXPORT, CHANGING, RETURN (DIFFERENT FROM FM).

"""" REQUIRMENT - WANT TO PASS THE VALUES AT RUNTIME AS PARAMETERS TO METHOD.

CLASS LCL_EMP DEFINITION.
  PUBLIC SECTION.
  METHODS : SET_EMP IMPORTING I_EMPNO TYPE I
                              I_ENAME TYPE C OPTIONAL
                              I_EMPDESIG TYPE C DEFAULT 'MANAGER',
                              GET_EMP.

  PROTECTED SECTION.
  DATA : EMPNO TYPE I,                 """" INSTANCE ATTRIBUTE.
         ENAME(20) TYPE C,
         EMPDESIG(20) TYPE C.

ENDCLASS.



CLASS LCL_EMP IMPLEMENTATION.
  METHOD SET_EMP.
    EMPNO = I_EMPNO.
    ENAME = I_ENAME.
    EMPDESIG = I_EMPDESIG.

  ENDMETHOD.

  METHOD GET_EMP.
    FORMAT COLOR 3.
    WRITE :/ EMPNO, ENAME, EMPDESIG.

    FORMAT COLOR OFF.
  ENDMETHOD.
ENDCLASS.



START-OF-SELECTION.

DATA OB1 TYPE REF TO LCL_EMP.

CREATE OBJECT OB1.

*CALL METHOD OB1->SET_EMP.           """" SYNTAX ERROR SINCE OBLIGATORY PARAMETERS ARE NOT BEING PASSED.


PARAMETERS : P_EMPNO TYPE I,
             P_ENAME(20) TYPE C,
             P_EMPDESIG(25) TYPE C.

CALL METHOD OB1->SET_EMP
EXPORTING
  I_EMPNO = P_EMPNO.


CALL METHOD OB1->GET_EMP.

ULINE.

DATA OB2 TYPE REF TO LCL_EMP.

CREATE OBJECT OB2.

CALL METHOD OB2->SET_EMP
EXPORTING
  I_EMPNO = P_EMPNO
  I_ENAME = P_ENAME.


CALL METHOD OB2->GET_EMP.


ULINE.
