REPORT ZOOPS_D9_P1.

******************* DAY 9 PROGRAM 1 ****************************

"""" TOPICS - 1) ABSTRACT CLASS




""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"""" THEORY

"""" EARLIER      CLASS -> DEFINITION -> DECLARING METHODS (5 METHODS).
"""" ABSTRACT CLASS -> CLASS WHICH CONTAINS ATLEAST  ONE ABSTRACT METHOD(A METHOD WHICH IS JUST DECLARED AND NOT IMPLEMENTED.)

"""" NOTE - IF THE CLASS CONTAINS ATLEAST ONE ABSTRACT METHOD THEN THE CLASS SHOULD ALSO BE DECLARED AS ABSTACT CLASS. WE WILL NEVER CREATE OUR OWN ABSTRACT CLASSES.
""""        WE SHOULD KNOW HOW TO WORK WITH ABSTRACT CLASSES WE WILL NEVER BE CREATING ABSTRACT CLASS.
""""        IF THE CLASS IS ABSTRACT THAT CLASS CANNOT BE INSTANTIATED MEANS WE CAN'T CREATE THE OBJECT FOR ABSTRACT CLASS.
""""        WE CAN CREATE THE OBJECT ONLY IF ALL THE METHODS ARE IMPLEMENTED.


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"""" Q - WHY A METHOD IS DECLARED AS ABSTRACT METHOD
"""" A - THE SAME METHOD HAS TO BE USED IN OTHER CLASSES BUT THE IMPLEMENTATION IS SPECIFIC TO THAT PARTICULAR CLASSES, IN THAT CASES WE DECLARE A METHOD AS ABSTRACT.

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

"""" REQ - TO CREATE ABSTRACT CLASS(RESTAURENT) AND CHEQUE INHERITING FROM RESTAURENT
"""" NOTE - PAYMENT METHOD IS ABSTRCT SINCE A CUSTOMER CAN MAKE PAYMENT BY USING CHEQUE, CREDIT CARD OR DEBIT CARD, SO WE DON'T KNOW THE IMPLEMENTATION.
""""        THE METHOD IS SAME BUT THE IMPLEMENTATION IS SPECIFIC TO RESPECTIVE CLASS.
""""        THE CLASS WHICHEVER IS INHERITING SUBCLASS MUST IMPLEMENT ABSTRACT METHOD, OTHERWISE THAT  SUBCLASS SHOULD ALSO BE DECLARED AS ABSTRACT.
 """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
 
 CLASS LCL_RESTAURENT DEFINITION ABSTRACT.                                         """" NOTE - IF A CLASS CONTAINS EVEN ONE ABSTRACT METHOD THEM THE CLASS SHOULD ALSO BE DECLARED AS ABSTRACT CLASS.
   PUBLIC SECTION.
      METHODS : STORE,                                                    """" INSTANCE METHODS
                DISPLAY,                                                           """" THE METHODS WHICH WE IMPLEMENT S CALLED AS NON-ABSTRACT METHOD / CONCRETE METHOD.
                PAYMENT ABSTRACT.                                                  """" ABSTRACT KEYWORD USED FOR ABSTRACT METHOD SINCE WE DON'T WANT TO ADD IMPLEMENTATION.
                                                                                   """" ABSTRACT METHOD ALSO CALLED AS NON CONCRETE METHOD.
      
*      CLASS-METHODS M1 ABSTRACT.                                                   """" ERROR - CAN'T REDEFINE STATIC METHODS AND THUS SHOULDN'T BE DECLARED AS ABSTRACT.
      
      
      
   PROTECTED SECTION.
      DATA : TABLENO TYPE I,                                              """" INSTANCE ATTRIBUTES.
             STEWARD TYPE STRING.
              
         
   
ENDCLASS. 
 

CLASS LCL_RESTAURENT IMPLEMENTATION.                                      """" SO OUT OF 3 METHODS WE DECLARED WE ARE IMPLEMENTING ONLY 2 METHODS.
  
  METHOD STORE.
    TABLENO = 4.
    STEWARD = 'RAJ'.
    
  ENDMETHOD.  
  
  METHOD DISPLAY.
    WRITE :/ TABLENO, STEWARD.
    
  ENDMETHOD.  
  
  
ENDCLASS.  
 
 
START-OF-SELECTION.
 
* DATA OB1 TYPE REF TO LCL_RESTAURENT.
* CREATE OBJECT OB1.                        """" ERROR - YOU CANNOT GENERATE INSTANCES OF ABSTRACT CLASS.
 
 """" NOTE - NOW SINCE WE NEED TO ACCESS INSTANCE METHOD WE NEED TO CREATE REFERENCE.
 
