REPORT ZOOPS_D5_P4.

********* DAY 5 PROGRAM 3 *************

"""" TOPICS - 1) INSTANCE AND STATIC ATTRIBUTES AND METHODS.
"""" SUMMARY - INSIDE INSTANCE METHOD WE CAN ACCESS ANY KIND OF COMPONENT. WHEREAS IN STATIC METHOD WE CAN ACCESS ALL COMPONENTS EXCEPT INSTANCE COMPONENTS.

CLASS LCL_ABC DEFINITION.
  PUBLIC SECTION.
    METHODS M1.                                  """" INSTANCE METHOD
    CLASS-METHODS M2.                            """" STATIC METHOD.

  PROTECTED SECTION.
    DATA X TYPE I.                               """" INSTANCE ATTRIBUTE.
    CLASS-DATA Y TYPE I.                         """" STATIC ATTRIBUTE.
    CONSTANTS Z TYPE I VALUE 10.                 """"
    TYPES M TYPE I.                              """" TYPES ONLY PROVIDES TEMPLATE.

ENDCLASS.

CLASS LCL_ABC IMPLEMENTATION.
  METHOD M1.
    WRITE :/ 'INSIDE INSTANCE METHOD M1 OF CLASS ABC CLASS'.
    """" NOTE - INSTANCE METHOD CAN ACCESS ANY KIND OF COMPONENTS.
    X = 10.
    Y = 12.
    DATA V_M TYPE M.                            """" USING THE ABOVE TYPES FROM PROTECTED SECTION.
    V_M = 13.

    WRITE :/ X,Y,Z,V_M.

  ENDMETHOD.

  METHOD M2.
    WRITE :/ 'INSIDE  STATIC METHOD M2'.
*    X = 21.                    """" X IS INSTANCE ATTRIBUTE WHICH I AM TRYING TO ACCESS INSIDE STATIC METHOD. ERROR - WITHIN STATIC METHOD YOU CAN ONLY ACCESS STATIC ATTRIBUTE.

    Y = 22.                    """" STATIC ATTRIBUTE.

    DATA LV_M  TYPE M.
    LV_M = 23.

    WRITE :/ Y,Z,LV_M.

  ENDMETHOD.

ENDCLASS.

"""" NOTE - STATIC METHODS CAN ACCESS ALL THE COMPONENTS EXCEPT INSTANCE COMPONENT.
"""" NOTE - INSTANCE METHOD CAN ACCESS ANY KIND OF COMPONENT.

START-OF-SELECTION.

CALL METHOD LCL_ABC=>M2.
*CALL METHOD LCL_ABC=>M1.         """" SYNTAX ERROR - YOU CAN ONLY USE CLASS METHODS => WITH STATIC METHODS.

ULINE.

DATA OB1 TYPE REF TO LCL_ABC.
CREATE OBJECT OB1.

CALL METHOD OB1->M2.             """"NOTE - STATIC METHOD CAN BE USED EITHER BY USING CLASS OR BY USING OBJECT.

ULINE.

CALL METHOD OB1->M1.

"""" SUMMARY - INSIDE INSTANCE METHOD WE CAN ACCESS ANY KIND OF COMPONENT. WHEREAS IN STATIC METHOD WE CAN ACCESS ALL COMPONENTS EXCEPT INSTANCE COMPONENTS.
