REPORT ZOOPS_D6_P4.

********** DAY 6 PROGRAM 4 ****************

"""" TOPICS - 1) STATIC ATTRIBUTE INSIDE PUBLIC SECTION WITH STATIC CONSTRUCTORS.

"""" NOTE - STATIC WILL BE EXECUTED WHEN WE CREATE THE FIRST OBJECT.
""""        STATIC CONSTRUCTOR WILL BE EXECUTED ONLY ONCE IN THE LIFETIME OF THE CLASS.
""""        IT WILL BE EXECUTED IN THE EITHER OF THE TWO CASES
""""        CASE 1 - WHEN WE ACCESS STATIC COMPONENT OF THE CLASS USING CLASS NAME BEFORE CREATING ANY OBJECT.
""""        CASE 2 - WHEN WE CREATE FIRST OBJECT OF THE CLASS BEFORE ACCESSING ANY STATIC COMPONENT
""""        SO IF WE COMMENT THE CALLING OF THE STATIC ATTRIBUTE -  STATIC CONSTRUCTOR WILL BE CALLED FIRST THEN INSTANCE CONSTRUCTOR.
""""

"""" DIFFERENCE BETWEEN INSTANCE AND STATIC CONSTRUCTOR?
"""" A - INSTANCE CONSTRUCTOR IS SPECIFIC TO OBJECT WHEREAS STATIC CONSTRUCTOR IS NOT SPECIFIC TO OBJECT.
""""     INSTANCE CONSTRUCTOR WILL BE EXECUTED ONCE IN THE LIFETIME OF EACH OBJECT WHEREAS STATIC OBJECT CAN BE EXECUTED IN THE LIFETIME OF CLASS.
""""     INSTANCE CONSTRUCTOR CAN CONTAIN IMPORTING PARAMETERS AND EXCEPTION WHERAS STATIC CONSTRUCTOR CAN CONTAIN NO PARAMETERS.


"""" DIFFERENCE BETWEEN NORMAL METHOD AND SPECIAL METHODS(CONSTRUCTORS).
"""" A- NORMAL - 1) CAN BE DECLARED IN ANY OF THE SECTION.
""""             2)SHOULD BE CALLED EXPLICTLY.
""""             3) CAN BE CALLED ANY NUMBER OF TIMES USING THE SAME OBJECT.
""""             4) CAN CONTAIN ANY TYPE OF PARAMETER.
""""             5) CAN RETURN ANY NUMBER OF VALUES.
""""    SPECIAL - 1) CAN BE DECLARED IN PUBLIC SECTION ONLY.
""""             2)WILL BE CALLED IMPLICTLY.
""""             3) INSTANCE CONSTRUCTOR WILL BE EXECUTED ONCE IN THE LIFETIME OF EACH OBJECT WHEREAS STATIC OBJECT CAN BE EXECUTED IN THE LIFETIME OF CLASS.
""""             4) INSTANCE CONSTRUCTOR CAN CONTAIN IMPORTING PARAMETERS AND EXCEPTION WHERAS STATIC CONSTRUCTOR CAN CONTAIN NO PARAMETERS.
""""             5) NEVER RETURNS ANY VALUE.
""""




"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

CLASS LCL_ABC DEFINITION.

  PUBLIC SECTION.
    METHODS CONSTRUCTOR.                                """" INSTANCE CONSTRUCTOR CAN CONTAIN IMPORTING PARAMETER AND EXCEPTION.
    CLASS-METHODS CLASS_CONSTRUCTOR.                    """" STATIC CONSTRUCTOR.CLASS-METHODS CLASS_CONSTRUCTOR IMPORTING X TYPE I.  ERROR - CAN'T CONTAIN ANY PARAMTER OR EXCEPTION.
    CLASS-DATA X TYPE I.

ENDCLASS.


CLASS LCL_ABC IMPLEMENTATION.

  METHOD CONSTRUCTOR.
    WRITE :/ 'INSIDE INSTANCE CONSTRUCTOR'.
  ENDMETHOD.

  METHOD CLASS_CONSTRUCTOR.
    WRITE :/ 'INSIDE STATIC CONSTRUCTOR'.
  ENDMETHOD.

ENDCLASS.


START-OF-SELECTION.

LCL_ABC=>X = 45.
ULINE.

"""" NOTE - IN THE EARLIER EXAMPLE STATIC GOT EXECUTED IN THE FIRST OBJECT.

FORMAT COLOR 1.
WRITE :/ 'FIRST OBJECT OB1 CREATED.'.

DATA OB1 TYPE REF TO LCL_ABC.
CREATE OBJECT OB1.

FORMAT COLOR OFF.

ULINE.



























"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
