REPORT ZOOPS_D4_P2.

************** DAY 4 PROG 2 **************



"""" TOPICS - 1) ACCESING GLOBAL CLASS CREATED IN SE24 AND CALLING THOSE ATTRIBUTES AND METHODS IN THIS PROGRAM.
"""" Q - HOW DO YOU CONVERT LOCAL CLASS TO GLOBAL CLASS?.
"""" A - SE24->OBJECT TYPE -> IMPORT-> LOCAL CLASSES IN PROG-> PUT PROGRAM NAME -> THEN ON THE LEFT OF SAVE CLICK IMPORT.



"""" NOTE - IN THE GLOCAL CLASS INCASE YOU WANT SOME DATA VARIBLE TO BE DECLARED AS INTERNAL TABLE THEN NEED TO DECLARED ANOTHER DATA VARIBLE WITH THE ABOVE TYPES IN THE SE24 AND THEN IN THE ATTRIB TAB OF CLASS REFERE THAT TO THE TYPES DECLARED.
""""        BASICALLY DO TYPE REFERENCE 2 TIMES FOR GETTING THE INTERNAL TABLE FOR THE DATA FIELD.


PARAMETERS : P_KUNNR TYPE KNA1-KUNNR.   """" NOTE - BY DEFAULT PARAMETERS ARE PASS BY REFERENCE(ANY CHANGES MADE IN THE FORMAL PARAMETERS WILL AUTOMATICALLY REFLECT ACTUALL PARAMETERS).


DATA OB1 TYPE REF TO ZOOPS_D4_P1.

CREATE OBJECT OB1.

CALL METHOD OB1->GETCUSTOMER
  EXPORTING
    I_KUNNR = P_KUNNR.
    

"""" 

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""


