REPORT ZOOPS_D4_P1.

******************** OOPS DAY 4 PROGRAM 1 ******************************


"""" TOPICS - 1)ATTRIBUTE - TYPES ATTRIBUTE() . 2) MODULARIZE THE BUSINESS LOGIC 3)PROTECTED METHOD .

"""" SUMMARY - 1ST METHOD GOT THE CUSTOMER DATA AND 2ND ONE DISPLAYED THE CUSTOMER ORDER DATA.
""""           3ND METHOD GOT THE SALES ORDER DATA AND 4TH METHOD DISPLAYED THE SALES ORDER DATA.


CLASS LCL_CUSTOMER DEFINITION. 
"""" (OR) CLASS LCL_CUSTOMER DEFINITION CREATE PUBLIC.
  PUBLIC SECTION.
      METHODS : GETCUSTOMER IMPORTING I_KUNNR TYPE KNA1-KUNNR.                              """" RESPONSIBLE ONLY FOR GETTING THE DATA LIKE CUSTOMER NAME, CUSTOMER CITY ALL THOSE.





  PROTECTED SECTION.
               METHODS DISPLAYCUSTOMER.                                                             """" FOR DISPLAYING THE DATA.  """" TAKING I_CUST NO TO AVOID CONFUSION.
               METHODS GETSALESORDERS IMPORTING I_CUSTNO TYPE KNA1-KUNNR.
               METHODS DISPLAYSALESORDERS.


                """" NOW TRYING TO RETURN CUSTOMER NAME AND CITY AS WORK AREA.
                TYPES : BEGIN OF TY_CUSTOMER,
                          NAME1 TYPE KNA1-NAME1,
                          NAME2 TYPE KNA1-NAME2,
                          ORT01 TYPE KNA1-ORT01,
                        END OF TY_CUSTOMER.


                """" NOW BASED ON THE ABOVE STRUCUTRE CREATING WORK AREA.

                DATA : WA_CUSTOMER TYPE TY_CUSTOMER.

                TYPES : BEGIN OF TY_SALES.
                          INCLUDE TYPE ZCVBAK.
                        TYPES END OF TY_SALES.

               DATA : T_SALES TYPE TABLE OF TY_SALES.                                        """"" DECLARING A INTERNAL TABLE SINCE THE ATTRIB CAN BE USED BY ALL THE METHODS AND INSTEAD IF WE DECLARED THIS INSIDE THE CLASS
                                                                                             """"" THEN IT CAN BE USED BY ALL THE METHODS ELSE IF IT WAS LOCAL THEN IT CAN BE ONLY USED BY ONLY THAT PARTICULAR METHOD.



ENDCLASS.


CLASS LCL_CUSTOMER IMPLEMENTATION.
  METHOD GETCUSTOMER.
    SELECT SINGLE NAME1 NAME2 ORT01                                       """" SO JUST RETRIVING THE DATA AND PUTTING IN THE WORK AREA.
      FROM KNA1
      INTO WA_CUSTOMER
      WHERE KUNNR = I_KUNNR.

      IF SY-SUBRC = 0.
        DISPLAYCUSTOMER( ).
        GETSALESORDERS( I_KUNNR ). """" OR GETSALESORDERS( EXPORTING I_CUSTNO = I_KUNNR).                                        """" SO WHATEVER THE CUSTOMER NUMBER THIS METHOD IS RECEIVING.
                                                              """" THIS OR CAN USE THE CALL METHOD FUNCTION.

      ELSE.
        MESSAGE 'NO CUSTOMER FOUND IN THE RECORD DATABASE OF PRODUCTION SYSTEM.' TYPE 'I'.

      ENDIF.

  ENDMETHOD.

  """" NOW NEED TO DISPLAY IT .
  METHOD DISPLAYCUSTOMER.
  FORMAT COLOR 3.
  WRITE :/ 'CUSTOMER DATA...'.
  WRITE :/ 'CUSTOMER FIRSTNAME:', WA_CUSTOMER-NAME1,
         / 'CUSTOMER SECONDNAME:', WA_CUSTOMER-NAME2,
         / 'CUSTOMER CITY:', WA_CUSTOMER-ORT01.
  FORMAT COLOR OFF.
  ENDMETHOD.

  """" DECLARING THE GETSALESORDERS METHOD IN THE END.


  METHOD GETSALESORDERS.
    """" NOW CUSTOMER MIGHT CONTAIN ANY NUMBER OF SALES ORDERS SO WE REQUIRE A INTERNAL TABLE AND THAT ITAB WE WANT TO USE IN GETSALESORDERS AND DISPLAY METHOD.
    """" STEPS TO CREATE ITAB - 1)DECLARE THE TYPES IN THE PROTECTED SECTION SO IT CAN'T BE CALLED OUTSIDE. 2) CREATE THE INTERNAL TABLE with DATA KEYWPRD.

    SELECT VBELN ERDAT ERZET ERNAM
      FROM VBAK
      INTO TABLE T_SALES
      WHERE KUNNR = I_CUSTNO.


    IF SY-SUBRC = 0.
        DISPLAYSALESORDERS( ).
    ELSE.
      MESSAGE 'NO SALES ORDERS.' TYPE 'I'.
    ENDIF.




  ENDMETHOD.

  METHOD DISPLAYSALESORDERS.
    """" HERE CAN DELCARE THE WORK AREA INSIDE THE METHOD ITSELF SINCE WE WANT TO ACCESS IT INSIDE THE WORK AREA ONLY.

    DATA : WA_SALES TYPE TY_SALES.
    FORMAT COLOR 7.
    DESCRIBE TABLE T_SALES.
    WRITE :/ 'NUMBER OF SALES ORDERS:', SY-TFILL.

    LOOP AT T_SALES INTO WA_SALES.
      WRITE :/ 'SALES DOCUMENT NUMBER :',WA_SALES-VBELN,
             / 'CREATION DATE :',WA_SALES-ERDAT,
             / 'CREATED BY :',WA_SALES-ERNAM,
             / 'CREATION TIME :',WA_SALES-ERZET.

    ENDLOOP.


  ENDMETHOD.


ENDCLASS.



START-OF-SELECTION.


DATA OB1 TYPE REF TO LCL_CUSTOMER.

CREATE OBJECT OB1.

"""" NOTE - BEFORE CALLING ANY METHOD WE NEED TO CHECK THE SIGNATURE OF THE METHOD.

PARAMETERS : P_KUNNR TYPE KNA1-KUNNR.

CALL METHOD OB1->GETCUSTOMER
EXPORTING I_KUNNR = P_KUNNR.                                                            """" SINCE I_KUNNR IS OBLIGATORY.


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
""" NOW DECLARING METHODS FOR GETTING THE SALES ORDER IN THE PROTECTED SECTION.


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

"""" NOW DOING THE ABOVE SAME EXAMPLE BY USING GLOBAL CLASS.

